"""Initial migration.

Revision ID: 2991aad697d9
Revises: 
Create Date: 2024-03-14 20:25:50.152681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2991aad697d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fs_uniquifier')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
