version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5436:5432"
    env_file:
      - ./web_for_msu_back/app/.env
    environment:
      POSTGRES_DB: emsh_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "db_data:/var/lib/postgresql/data"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U user" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: ./web_for_msu_back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      FLASK_ENV: production
    networks:
      - app-network

  frontend:
    build:
      context: ./web_for_msu_front
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/nginx/ssl/:/etc/nginx/ssl/"
    depends_on:
      - postgres
      - backend
      - frontend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
