from .account import AccountForm
from .course import CourseForm
from .course_file import CourseFileForm
from .login import LoginForm
from .logout import LogoutForm
from .marks import MarksForm
from .pupil_marks import PupilMarksForm
from .registration import RegistrationForm
from .schedule import ScheduleForm
from .teacher_course import TeacherCourseForm
from .teacher_registration import TeacherRegistrationForm
