from .login import LoginForm
from .account import AccountForm
from .registration import RegistrationForm
from .teacher_registration import TeacherRegistrationForm
from .logout import LogoutForm
from .course import CourseForm
from .teacher_course import TeacherCourseForm
from .schedule import ScheduleForm
from .course_file import CourseFileForm
