from .user import User
from .role import Role
from .pupil import Pupil
from .teacher import Teacher
from .course import Course
from .teacher_course import TeacherCourse
from .schedule import Schedule
from .pupil_course import PupilCourse
from .mark import Mark
