from WEB_FOR_MSU import db


class Pupil(db.Model):
    __tablename__ = 'pupil'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', backref='pupil')
    name = db.Column(db.String(), nullable=False)
    surname = db.Column(db.String(), nullable=False)
    patronymic = db.Column(db.String(), nullable=False)
    birth_date = db.Column(db.Date(), nullable=False)
    nickname = db.Column(db.String(), nullable=False)
    telegram = db.Column(db.String())
    vk = db.Column(db.String())
    phone = db.Column(db.String(), nullable=False)
    passport_number = db.Column(db.String(), nullable=False)
    passport_series = db.Column(db.String(), nullable=False)
    passport_date = db.Column(db.Date(), nullable=False)
    passport_issued_by = db.Column(db.String(), nullable=False)
    registration_address = db.Column(db.String(), nullable=False)
    parent1_name = db.Column(db.String(), nullable=False)
    parent1_surname = db.Column(db.String(), nullable=False)
    parent1_patronymic = db.Column(db.String(), nullable=False)
    parent1_phone = db.Column(db.String(), nullable=False)
    parent1_email = db.Column(db.String(), nullable=False)
    parent2_name = db.Column(db.String())
    parent2_surname = db.Column(db.String())
    parent2_patronymic = db.Column(db.String())
    parent2_phone = db.Column(db.String())
    parent2_email = db.Column(db.String())
    school = db.Column(db.String(), nullable=False)
    school_grade = db.Column(db.Integer, nullable=False)
    emsh_grade = db.Column(db.Integer, nullable=False)
    enroll_way = db.Column(db.String(), nullable=False)
    organization_fee = db.Column(db.String())
    present_FA = db.Column(db.String())
    security_key_card = db.Column(db.String())
    graduating = db.Column(db.Boolean, default=False)
    achievements = db.Column(db.String())
    courses = db.relationship('Course', secondary='pupil_course', backref='pupils')
    # TODO: add foreign keys: KNR_id	VS_id	NS_id	OK_id	OC_id	LS_ids	graduation_id
