version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: emsh_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123