from .course import Course
from .formula import Formula
from .mark import Mark
from .news import News
from .pupil import Pupil
from .pupil_course import PupilCourse
from .role import Role
from .schedule import Schedule
from .teacher import Teacher
from .teacher_course import TeacherCourse
from .user import User
from .user_role import user_role
from .course_registration_period import CourseRegistrationPeriod
from .registration_period import RegistrationPeriod
from .event_date import EventDate
