from .course import CourseItem
from .formula import Formula
from .mark import Mark
from .pupil import Pupil
from .pupil_course import PupilCourse
from .role import Role
from .schedule import Schedule
from .teacher import Teacher
from .teacher_course import TeacherCourse
from .user import User
from .user_role import user_role
from .news import News
