version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: emsh_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass